version: '3.8'

services:
  db:
    image: postgres:14
    container_name: postgres_container
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: wissen
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: springboot_container
    ports:
      - "8181:8080"
    depends_on:
      - db