spring.application.name=emp-docker
spring.datasource.url=jdbc:postgresql://db:5432/mydb
spring.datasource.username=postgres
spring.datasource.password=wissen

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true